// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	constant "nh-be/internal/constant"

	mock "github.com/stretchr/testify/mock"

	observation "nh-be/internal/features/observation"

	uuid "github.com/google/uuid"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CreateObservation provides a mock function with given fields: ctx, expId, procStepId, _a3
func (_m *Repository) CreateObservation(ctx context.Context, expId uuid.UUID, procStepId uuid.UUID, _a3 observation.Observation) (observation.Observation, error) {
	ret := _m.Called(ctx, expId, procStepId, _a3)

	if len(ret) == 0 {
		panic("no return value specified for CreateObservation")
	}

	var r0 observation.Observation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, observation.Observation) (observation.Observation, error)); ok {
		return rf(ctx, expId, procStepId, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, observation.Observation) observation.Observation); ok {
		r0 = rf(ctx, expId, procStepId, _a3)
	} else {
		r0 = ret.Get(0).(observation.Observation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, observation.Observation) error); ok {
		r1 = rf(ctx, expId, procStepId, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CreateObservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateObservation'
type Repository_CreateObservation_Call struct {
	*mock.Call
}

// CreateObservation is a helper method to define mock.On call
//   - ctx context.Context
//   - expId uuid.UUID
//   - procStepId uuid.UUID
//   - _a3 observation.Observation
func (_e *Repository_Expecter) CreateObservation(ctx interface{}, expId interface{}, procStepId interface{}, _a3 interface{}) *Repository_CreateObservation_Call {
	return &Repository_CreateObservation_Call{Call: _e.mock.On("CreateObservation", ctx, expId, procStepId, _a3)}
}

func (_c *Repository_CreateObservation_Call) Run(run func(ctx context.Context, expId uuid.UUID, procStepId uuid.UUID, _a3 observation.Observation)) *Repository_CreateObservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(observation.Observation))
	})
	return _c
}

func (_c *Repository_CreateObservation_Call) Return(_a0 observation.Observation, _a1 error) *Repository_CreateObservation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CreateObservation_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, observation.Observation) (observation.Observation, error)) *Repository_CreateObservation_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllObsByExpIDAndProcID provides a mock function with given fields: ctx, expId, procId, offset, limit, sortBy, sortOrder
func (_m *Repository) GetAllObsByExpIDAndProcID(ctx context.Context, expId uuid.UUID, procId uuid.UUID, offset int, limit int, sortBy *string, sortOrder *constant.Order) ([]observation.ObservationMetadata, int64, error) {
	ret := _m.Called(ctx, expId, procId, offset, limit, sortBy, sortOrder)

	if len(ret) == 0 {
		panic("no return value specified for GetAllObsByExpIDAndProcID")
	}

	var r0 []observation.ObservationMetadata
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int, *string, *constant.Order) ([]observation.ObservationMetadata, int64, error)); ok {
		return rf(ctx, expId, procId, offset, limit, sortBy, sortOrder)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int, *string, *constant.Order) []observation.ObservationMetadata); ok {
		r0 = rf(ctx, expId, procId, offset, limit, sortBy, sortOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]observation.ObservationMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int, int, *string, *constant.Order) int64); ok {
		r1 = rf(ctx, expId, procId, offset, limit, sortBy, sortOrder)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, int, int, *string, *constant.Order) error); ok {
		r2 = rf(ctx, expId, procId, offset, limit, sortBy, sortOrder)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repository_GetAllObsByExpIDAndProcID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllObsByExpIDAndProcID'
type Repository_GetAllObsByExpIDAndProcID_Call struct {
	*mock.Call
}

// GetAllObsByExpIDAndProcID is a helper method to define mock.On call
//   - ctx context.Context
//   - expId uuid.UUID
//   - procId uuid.UUID
//   - offset int
//   - limit int
//   - sortBy *string
//   - sortOrder *constant.Order
func (_e *Repository_Expecter) GetAllObsByExpIDAndProcID(ctx interface{}, expId interface{}, procId interface{}, offset interface{}, limit interface{}, sortBy interface{}, sortOrder interface{}) *Repository_GetAllObsByExpIDAndProcID_Call {
	return &Repository_GetAllObsByExpIDAndProcID_Call{Call: _e.mock.On("GetAllObsByExpIDAndProcID", ctx, expId, procId, offset, limit, sortBy, sortOrder)}
}

func (_c *Repository_GetAllObsByExpIDAndProcID_Call) Run(run func(ctx context.Context, expId uuid.UUID, procId uuid.UUID, offset int, limit int, sortBy *string, sortOrder *constant.Order)) *Repository_GetAllObsByExpIDAndProcID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int), args[4].(int), args[5].(*string), args[6].(*constant.Order))
	})
	return _c
}

func (_c *Repository_GetAllObsByExpIDAndProcID_Call) Return(_a0 []observation.ObservationMetadata, _a1 int64, _a2 error) *Repository_GetAllObsByExpIDAndProcID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_GetAllObsByExpIDAndProcID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int, int, *string, *constant.Order) ([]observation.ObservationMetadata, int64, error)) *Repository_GetAllObsByExpIDAndProcID_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
