// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	constant "nh-be/internal/constant"

	mock "github.com/stretchr/testify/mock"

	observation "nh-be/internal/features/observation"

	uuid "github.com/google/uuid"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CreateObservation provides a mock function with given fields: ctx, expId, procStepId, input
func (_m *Service) CreateObservation(ctx context.Context, expId uuid.UUID, procStepId uuid.UUID, input observation.CreateObservationInput) (observation.CreatedObservationResponseDto, error) {
	ret := _m.Called(ctx, expId, procStepId, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateObservation")
	}

	var r0 observation.CreatedObservationResponseDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, observation.CreateObservationInput) (observation.CreatedObservationResponseDto, error)); ok {
		return rf(ctx, expId, procStepId, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, observation.CreateObservationInput) observation.CreatedObservationResponseDto); ok {
		r0 = rf(ctx, expId, procStepId, input)
	} else {
		r0 = ret.Get(0).(observation.CreatedObservationResponseDto)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, observation.CreateObservationInput) error); ok {
		r1 = rf(ctx, expId, procStepId, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_CreateObservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateObservation'
type Service_CreateObservation_Call struct {
	*mock.Call
}

// CreateObservation is a helper method to define mock.On call
//   - ctx context.Context
//   - expId uuid.UUID
//   - procStepId uuid.UUID
//   - input observation.CreateObservationInput
func (_e *Service_Expecter) CreateObservation(ctx interface{}, expId interface{}, procStepId interface{}, input interface{}) *Service_CreateObservation_Call {
	return &Service_CreateObservation_Call{Call: _e.mock.On("CreateObservation", ctx, expId, procStepId, input)}
}

func (_c *Service_CreateObservation_Call) Run(run func(ctx context.Context, expId uuid.UUID, procStepId uuid.UUID, input observation.CreateObservationInput)) *Service_CreateObservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(observation.CreateObservationInput))
	})
	return _c
}

func (_c *Service_CreateObservation_Call) Return(_a0 observation.CreatedObservationResponseDto, _a1 error) *Service_CreateObservation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_CreateObservation_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, observation.CreateObservationInput) (observation.CreatedObservationResponseDto, error)) *Service_CreateObservation_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllObservations provides a mock function with given fields: ctx, expId, procId, offset, limit, sortBy, sortOrder
func (_m *Service) GetAllObservations(ctx context.Context, expId uuid.UUID, procId uuid.UUID, offset int, limit int, sortBy *string, sortOrder *constant.Order) ([]observation.ObservationsResponseDto, int64, error) {
	ret := _m.Called(ctx, expId, procId, offset, limit, sortBy, sortOrder)

	if len(ret) == 0 {
		panic("no return value specified for GetAllObservations")
	}

	var r0 []observation.ObservationsResponseDto
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int, *string, *constant.Order) ([]observation.ObservationsResponseDto, int64, error)); ok {
		return rf(ctx, expId, procId, offset, limit, sortBy, sortOrder)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int, *string, *constant.Order) []observation.ObservationsResponseDto); ok {
		r0 = rf(ctx, expId, procId, offset, limit, sortBy, sortOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]observation.ObservationsResponseDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int, int, *string, *constant.Order) int64); ok {
		r1 = rf(ctx, expId, procId, offset, limit, sortBy, sortOrder)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, int, int, *string, *constant.Order) error); ok {
		r2 = rf(ctx, expId, procId, offset, limit, sortBy, sortOrder)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Service_GetAllObservations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllObservations'
type Service_GetAllObservations_Call struct {
	*mock.Call
}

// GetAllObservations is a helper method to define mock.On call
//   - ctx context.Context
//   - expId uuid.UUID
//   - procId uuid.UUID
//   - offset int
//   - limit int
//   - sortBy *string
//   - sortOrder *constant.Order
func (_e *Service_Expecter) GetAllObservations(ctx interface{}, expId interface{}, procId interface{}, offset interface{}, limit interface{}, sortBy interface{}, sortOrder interface{}) *Service_GetAllObservations_Call {
	return &Service_GetAllObservations_Call{Call: _e.mock.On("GetAllObservations", ctx, expId, procId, offset, limit, sortBy, sortOrder)}
}

func (_c *Service_GetAllObservations_Call) Run(run func(ctx context.Context, expId uuid.UUID, procId uuid.UUID, offset int, limit int, sortBy *string, sortOrder *constant.Order)) *Service_GetAllObservations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(int), args[4].(int), args[5].(*string), args[6].(*constant.Order))
	})
	return _c
}

func (_c *Service_GetAllObservations_Call) Return(_a0 []observation.ObservationsResponseDto, _a1 int64, _a2 error) *Service_GetAllObservations_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Service_GetAllObservations_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, int, int, *string, *constant.Order) ([]observation.ObservationsResponseDto, int64, error)) *Service_GetAllObservations_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
