with-expecter: true
testonly: false
inpackage: false
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
mockname: "{{.InterfaceName}}"
filename: "{{.InterfaceName | snakecase}}.go"
packages:
  nh-be/internal/features/auth:
    interfaces:
      Repository:
      Service:
  nh-be/internal/features/user:
    interfaces:
      Repository:
      Service:
  nh-be/internal/features/permission:
    interfaces:
      Repository:
      Service:
  nh-be/internal/features/experiment:
    interfaces:
      Repository:
      Service:
  nh-be/internal/features/experiment/result:
    interfaces:
      Repository:
      Service:
  nh-be/internal/features/procedure:
    interfaces:
      Repository:
      Service:
  nh-be/internal/features/observation:
    interfaces:
      Repository:
      Service:

