version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: noheir_api
    env_file: .env
    environment:
      GIN_MODE: ${GIN_MODE}
    ports:
      - "8080:8080"
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
