// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	permission "nh-be/internal/features/permission"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CreatePermissionGroup provides a mock function with given fields: ctx, pg
func (_m *Repository) CreatePermissionGroup(ctx context.Context, pg *permission.PermissionGroup) error {
	ret := _m.Called(ctx, pg)

	if len(ret) == 0 {
		panic("no return value specified for CreatePermissionGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *permission.PermissionGroup) error); ok {
		r0 = rf(ctx, pg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_CreatePermissionGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePermissionGroup'
type Repository_CreatePermissionGroup_Call struct {
	*mock.Call
}

// CreatePermissionGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - pg *permission.PermissionGroup
func (_e *Repository_Expecter) CreatePermissionGroup(ctx interface{}, pg interface{}) *Repository_CreatePermissionGroup_Call {
	return &Repository_CreatePermissionGroup_Call{Call: _e.mock.On("CreatePermissionGroup", ctx, pg)}
}

func (_c *Repository_CreatePermissionGroup_Call) Run(run func(ctx context.Context, pg *permission.PermissionGroup)) *Repository_CreatePermissionGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*permission.PermissionGroup))
	})
	return _c
}

func (_c *Repository_CreatePermissionGroup_Call) Return(_a0 error) *Repository_CreatePermissionGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_CreatePermissionGroup_Call) RunAndReturn(run func(context.Context, *permission.PermissionGroup) error) *Repository_CreatePermissionGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePermissionGroup provides a mock function with given fields: ctx, id
func (_m *Repository) DeletePermissionGroup(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePermissionGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_DeletePermissionGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePermissionGroup'
type Repository_DeletePermissionGroup_Call struct {
	*mock.Call
}

// DeletePermissionGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Repository_Expecter) DeletePermissionGroup(ctx interface{}, id interface{}) *Repository_DeletePermissionGroup_Call {
	return &Repository_DeletePermissionGroup_Call{Call: _e.mock.On("DeletePermissionGroup", ctx, id)}
}

func (_c *Repository_DeletePermissionGroup_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Repository_DeletePermissionGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_DeletePermissionGroup_Call) Return(_a0 error) *Repository_DeletePermissionGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_DeletePermissionGroup_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *Repository_DeletePermissionGroup_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllPermissionGroups provides a mock function with given fields: ctx, search, permissionIds, offset, limit
func (_m *Repository) FindAllPermissionGroups(ctx context.Context, search string, permissionIds []uuid.UUID, offset int, limit int) ([]permission.PermissionGroup, int64, error) {
	ret := _m.Called(ctx, search, permissionIds, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPermissionGroups")
	}

	var r0 []permission.PermissionGroup
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []uuid.UUID, int, int) ([]permission.PermissionGroup, int64, error)); ok {
		return rf(ctx, search, permissionIds, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []uuid.UUID, int, int) []permission.PermissionGroup); ok {
		r0 = rf(ctx, search, permissionIds, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]permission.PermissionGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []uuid.UUID, int, int) int64); ok {
		r1 = rf(ctx, search, permissionIds, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, []uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, search, permissionIds, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repository_FindAllPermissionGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllPermissionGroups'
type Repository_FindAllPermissionGroups_Call struct {
	*mock.Call
}

// FindAllPermissionGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
//   - permissionIds []uuid.UUID
//   - offset int
//   - limit int
func (_e *Repository_Expecter) FindAllPermissionGroups(ctx interface{}, search interface{}, permissionIds interface{}, offset interface{}, limit interface{}) *Repository_FindAllPermissionGroups_Call {
	return &Repository_FindAllPermissionGroups_Call{Call: _e.mock.On("FindAllPermissionGroups", ctx, search, permissionIds, offset, limit)}
}

func (_c *Repository_FindAllPermissionGroups_Call) Run(run func(ctx context.Context, search string, permissionIds []uuid.UUID, offset int, limit int)) *Repository_FindAllPermissionGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]uuid.UUID), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *Repository_FindAllPermissionGroups_Call) Return(_a0 []permission.PermissionGroup, _a1 int64, _a2 error) *Repository_FindAllPermissionGroups_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_FindAllPermissionGroups_Call) RunAndReturn(run func(context.Context, string, []uuid.UUID, int, int) ([]permission.PermissionGroup, int64, error)) *Repository_FindAllPermissionGroups_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllPermissions provides a mock function with given fields: ctx, name
func (_m *Repository) FindAllPermissions(ctx context.Context, name string) ([]permission.Permission, int64, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPermissions")
	}

	var r0 []permission.Permission
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]permission.Permission, int64, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []permission.Permission); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]permission.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) int64); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, name)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repository_FindAllPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllPermissions'
type Repository_FindAllPermissions_Call struct {
	*mock.Call
}

// FindAllPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Repository_Expecter) FindAllPermissions(ctx interface{}, name interface{}) *Repository_FindAllPermissions_Call {
	return &Repository_FindAllPermissions_Call{Call: _e.mock.On("FindAllPermissions", ctx, name)}
}

func (_c *Repository_FindAllPermissions_Call) Run(run func(ctx context.Context, name string)) *Repository_FindAllPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_FindAllPermissions_Call) Return(_a0 []permission.Permission, _a1 int64, _a2 error) *Repository_FindAllPermissions_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_FindAllPermissions_Call) RunAndReturn(run func(context.Context, string) ([]permission.Permission, int64, error)) *Repository_FindAllPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// FindIDByID provides a mock function with given fields: ctx, id
func (_m *Repository) FindIDByID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindIDByID")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (uuid.UUID, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) uuid.UUID); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindIDByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIDByID'
type Repository_FindIDByID_Call struct {
	*mock.Call
}

// FindIDByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Repository_Expecter) FindIDByID(ctx interface{}, id interface{}) *Repository_FindIDByID_Call {
	return &Repository_FindIDByID_Call{Call: _e.mock.On("FindIDByID", ctx, id)}
}

func (_c *Repository_FindIDByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Repository_FindIDByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_FindIDByID_Call) Return(_a0 uuid.UUID, _a1 error) *Repository_FindIDByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindIDByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (uuid.UUID, error)) *Repository_FindIDByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindIDByIDs provides a mock function with given fields: ctx, ids
func (_m *Repository) FindIDByIDs(ctx context.Context, ids []uuid.UUID) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindIDByIDs")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]uuid.UUID, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []uuid.UUID); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindIDByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIDByIDs'
type Repository_FindIDByIDs_Call struct {
	*mock.Call
}

// FindIDByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *Repository_Expecter) FindIDByIDs(ctx interface{}, ids interface{}) *Repository_FindIDByIDs_Call {
	return &Repository_FindIDByIDs_Call{Call: _e.mock.On("FindIDByIDs", ctx, ids)}
}

func (_c *Repository_FindIDByIDs_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *Repository_FindIDByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *Repository_FindIDByIDs_Call) Return(_a0 []uuid.UUID, _a1 error) *Repository_FindIDByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindIDByIDs_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]uuid.UUID, error)) *Repository_FindIDByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindPermissionByID provides a mock function with given fields: ctx, id
func (_m *Repository) FindPermissionByID(ctx context.Context, id uuid.UUID) (*permission.Permission, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindPermissionByID")
	}

	var r0 *permission.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*permission.Permission, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *permission.Permission); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*permission.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindPermissionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPermissionByID'
type Repository_FindPermissionByID_Call struct {
	*mock.Call
}

// FindPermissionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Repository_Expecter) FindPermissionByID(ctx interface{}, id interface{}) *Repository_FindPermissionByID_Call {
	return &Repository_FindPermissionByID_Call{Call: _e.mock.On("FindPermissionByID", ctx, id)}
}

func (_c *Repository_FindPermissionByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Repository_FindPermissionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_FindPermissionByID_Call) Return(_a0 *permission.Permission, _a1 error) *Repository_FindPermissionByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindPermissionByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*permission.Permission, error)) *Repository_FindPermissionByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPermissionGroupByID provides a mock function with given fields: ctx, id
func (_m *Repository) FindPermissionGroupByID(ctx context.Context, id uuid.UUID) (*permission.PermissionGroup, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindPermissionGroupByID")
	}

	var r0 *permission.PermissionGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*permission.PermissionGroup, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *permission.PermissionGroup); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*permission.PermissionGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindPermissionGroupByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPermissionGroupByID'
type Repository_FindPermissionGroupByID_Call struct {
	*mock.Call
}

// FindPermissionGroupByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Repository_Expecter) FindPermissionGroupByID(ctx interface{}, id interface{}) *Repository_FindPermissionGroupByID_Call {
	return &Repository_FindPermissionGroupByID_Call{Call: _e.mock.On("FindPermissionGroupByID", ctx, id)}
}

func (_c *Repository_FindPermissionGroupByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Repository_FindPermissionGroupByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_FindPermissionGroupByID_Call) Return(_a0 *permission.PermissionGroup, _a1 error) *Repository_FindPermissionGroupByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindPermissionGroupByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*permission.PermissionGroup, error)) *Repository_FindPermissionGroupByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPermissionGroupByName provides a mock function with given fields: ctx, name
func (_m *Repository) FindPermissionGroupByName(ctx context.Context, name string) (*permission.PermissionGroup, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindPermissionGroupByName")
	}

	var r0 *permission.PermissionGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*permission.PermissionGroup, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *permission.PermissionGroup); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*permission.PermissionGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindPermissionGroupByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPermissionGroupByName'
type Repository_FindPermissionGroupByName_Call struct {
	*mock.Call
}

// FindPermissionGroupByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Repository_Expecter) FindPermissionGroupByName(ctx interface{}, name interface{}) *Repository_FindPermissionGroupByName_Call {
	return &Repository_FindPermissionGroupByName_Call{Call: _e.mock.On("FindPermissionGroupByName", ctx, name)}
}

func (_c *Repository_FindPermissionGroupByName_Call) Run(run func(ctx context.Context, name string)) *Repository_FindPermissionGroupByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_FindPermissionGroupByName_Call) Return(_a0 *permission.PermissionGroup, _a1 error) *Repository_FindPermissionGroupByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindPermissionGroupByName_Call) RunAndReturn(run func(context.Context, string) (*permission.PermissionGroup, error)) *Repository_FindPermissionGroupByName_Call {
	_c.Call.Return(run)
	return _c
}

// FindPermissionGroupsByIDs provides a mock function with given fields: ctx, ids
func (_m *Repository) FindPermissionGroupsByIDs(ctx context.Context, ids []uuid.UUID) ([]permission.PermissionGroup, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindPermissionGroupsByIDs")
	}

	var r0 []permission.PermissionGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]permission.PermissionGroup, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []permission.PermissionGroup); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]permission.PermissionGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindPermissionGroupsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPermissionGroupsByIDs'
type Repository_FindPermissionGroupsByIDs_Call struct {
	*mock.Call
}

// FindPermissionGroupsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *Repository_Expecter) FindPermissionGroupsByIDs(ctx interface{}, ids interface{}) *Repository_FindPermissionGroupsByIDs_Call {
	return &Repository_FindPermissionGroupsByIDs_Call{Call: _e.mock.On("FindPermissionGroupsByIDs", ctx, ids)}
}

func (_c *Repository_FindPermissionGroupsByIDs_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *Repository_FindPermissionGroupsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *Repository_FindPermissionGroupsByIDs_Call) Return(_a0 []permission.PermissionGroup, _a1 error) *Repository_FindPermissionGroupsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindPermissionGroupsByIDs_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]permission.PermissionGroup, error)) *Repository_FindPermissionGroupsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindPermissionsByIDs provides a mock function with given fields: ctx, ids
func (_m *Repository) FindPermissionsByIDs(ctx context.Context, ids []uuid.UUID) ([]permission.Permission, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindPermissionsByIDs")
	}

	var r0 []permission.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]permission.Permission, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []permission.Permission); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]permission.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindPermissionsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPermissionsByIDs'
type Repository_FindPermissionsByIDs_Call struct {
	*mock.Call
}

// FindPermissionsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *Repository_Expecter) FindPermissionsByIDs(ctx interface{}, ids interface{}) *Repository_FindPermissionsByIDs_Call {
	return &Repository_FindPermissionsByIDs_Call{Call: _e.mock.On("FindPermissionsByIDs", ctx, ids)}
}

func (_c *Repository_FindPermissionsByIDs_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *Repository_FindPermissionsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *Repository_FindPermissionsByIDs_Call) Return(_a0 []permission.Permission, _a1 error) *Repository_FindPermissionsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindPermissionsByIDs_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]permission.Permission, error)) *Repository_FindPermissionsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserPermissionCodeNames provides a mock function with given fields: ctx, userId
func (_m *Repository) FindUserPermissionCodeNames(ctx context.Context, userId uuid.UUID) ([]string, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for FindUserPermissionCodeNames")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]string, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []string); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindUserPermissionCodeNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserPermissionCodeNames'
type Repository_FindUserPermissionCodeNames_Call struct {
	*mock.Call
}

// FindUserPermissionCodeNames is a helper method to define mock.On call
//   - ctx context.Context
//   - userId uuid.UUID
func (_e *Repository_Expecter) FindUserPermissionCodeNames(ctx interface{}, userId interface{}) *Repository_FindUserPermissionCodeNames_Call {
	return &Repository_FindUserPermissionCodeNames_Call{Call: _e.mock.On("FindUserPermissionCodeNames", ctx, userId)}
}

func (_c *Repository_FindUserPermissionCodeNames_Call) Run(run func(ctx context.Context, userId uuid.UUID)) *Repository_FindUserPermissionCodeNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_FindUserPermissionCodeNames_Call) Return(_a0 []string, _a1 error) *Repository_FindUserPermissionCodeNames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindUserPermissionCodeNames_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]string, error)) *Repository_FindUserPermissionCodeNames_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePermissionGroup provides a mock function with given fields: ctx, id, pg
func (_m *Repository) UpdatePermissionGroup(ctx context.Context, id uuid.UUID, pg *permission.PermissionGroup) error {
	ret := _m.Called(ctx, id, pg)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePermissionGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *permission.PermissionGroup) error); ok {
		r0 = rf(ctx, id, pg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdatePermissionGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePermissionGroup'
type Repository_UpdatePermissionGroup_Call struct {
	*mock.Call
}

// UpdatePermissionGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - pg *permission.PermissionGroup
func (_e *Repository_Expecter) UpdatePermissionGroup(ctx interface{}, id interface{}, pg interface{}) *Repository_UpdatePermissionGroup_Call {
	return &Repository_UpdatePermissionGroup_Call{Call: _e.mock.On("UpdatePermissionGroup", ctx, id, pg)}
}

func (_c *Repository_UpdatePermissionGroup_Call) Run(run func(ctx context.Context, id uuid.UUID, pg *permission.PermissionGroup)) *Repository_UpdatePermissionGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*permission.PermissionGroup))
	})
	return _c
}

func (_c *Repository_UpdatePermissionGroup_Call) Return(_a0 error) *Repository_UpdatePermissionGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdatePermissionGroup_Call) RunAndReturn(run func(context.Context, uuid.UUID, *permission.PermissionGroup) error) *Repository_UpdatePermissionGroup_Call {
	_c.Call.Return(run)
	return _c
}

// WithTransaction provides a mock function with given fields: ctx, fn
func (_m *Repository) WithTransaction(ctx context.Context, fn func(permission.Repository) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(permission.Repository) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type Repository_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(permission.Repository) error
func (_e *Repository_Expecter) WithTransaction(ctx interface{}, fn interface{}) *Repository_WithTransaction_Call {
	return &Repository_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx, fn)}
}

func (_c *Repository_WithTransaction_Call) Run(run func(ctx context.Context, fn func(permission.Repository) error)) *Repository_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(permission.Repository) error))
	})
	return _c
}

func (_c *Repository_WithTransaction_Call) Return(_a0 error) *Repository_WithTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_WithTransaction_Call) RunAndReturn(run func(context.Context, func(permission.Repository) error) error) *Repository_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
