// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	permission "nh-be/internal/features/permission"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CreatePermissionGroup provides a mock function with given fields: ctx, permissionGroup
func (_m *Service) CreatePermissionGroup(ctx context.Context, permissionGroup *permission.PermissionGroupInput) error {
	ret := _m.Called(ctx, permissionGroup)

	if len(ret) == 0 {
		panic("no return value specified for CreatePermissionGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *permission.PermissionGroupInput) error); ok {
		r0 = rf(ctx, permissionGroup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_CreatePermissionGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePermissionGroup'
type Service_CreatePermissionGroup_Call struct {
	*mock.Call
}

// CreatePermissionGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - permissionGroup *permission.PermissionGroupInput
func (_e *Service_Expecter) CreatePermissionGroup(ctx interface{}, permissionGroup interface{}) *Service_CreatePermissionGroup_Call {
	return &Service_CreatePermissionGroup_Call{Call: _e.mock.On("CreatePermissionGroup", ctx, permissionGroup)}
}

func (_c *Service_CreatePermissionGroup_Call) Run(run func(ctx context.Context, permissionGroup *permission.PermissionGroupInput)) *Service_CreatePermissionGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*permission.PermissionGroupInput))
	})
	return _c
}

func (_c *Service_CreatePermissionGroup_Call) Return(_a0 error) *Service_CreatePermissionGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_CreatePermissionGroup_Call) RunAndReturn(run func(context.Context, *permission.PermissionGroupInput) error) *Service_CreatePermissionGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePermissionGroup provides a mock function with given fields: ctx, id
func (_m *Service) DeletePermissionGroup(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePermissionGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_DeletePermissionGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePermissionGroup'
type Service_DeletePermissionGroup_Call struct {
	*mock.Call
}

// DeletePermissionGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Service_Expecter) DeletePermissionGroup(ctx interface{}, id interface{}) *Service_DeletePermissionGroup_Call {
	return &Service_DeletePermissionGroup_Call{Call: _e.mock.On("DeletePermissionGroup", ctx, id)}
}

func (_c *Service_DeletePermissionGroup_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Service_DeletePermissionGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Service_DeletePermissionGroup_Call) Return(_a0 error) *Service_DeletePermissionGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_DeletePermissionGroup_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *Service_DeletePermissionGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllPermissionGroups provides a mock function with given fields: ctx, search, permissionIds, page, pageSize
func (_m *Service) GetAllPermissionGroups(ctx context.Context, search string, permissionIds []uuid.UUID, page int, pageSize int) ([]permission.PermissionGroup, int64, error) {
	ret := _m.Called(ctx, search, permissionIds, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPermissionGroups")
	}

	var r0 []permission.PermissionGroup
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []uuid.UUID, int, int) ([]permission.PermissionGroup, int64, error)); ok {
		return rf(ctx, search, permissionIds, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []uuid.UUID, int, int) []permission.PermissionGroup); ok {
		r0 = rf(ctx, search, permissionIds, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]permission.PermissionGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []uuid.UUID, int, int) int64); ok {
		r1 = rf(ctx, search, permissionIds, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, []uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, search, permissionIds, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Service_GetAllPermissionGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllPermissionGroups'
type Service_GetAllPermissionGroups_Call struct {
	*mock.Call
}

// GetAllPermissionGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
//   - permissionIds []uuid.UUID
//   - page int
//   - pageSize int
func (_e *Service_Expecter) GetAllPermissionGroups(ctx interface{}, search interface{}, permissionIds interface{}, page interface{}, pageSize interface{}) *Service_GetAllPermissionGroups_Call {
	return &Service_GetAllPermissionGroups_Call{Call: _e.mock.On("GetAllPermissionGroups", ctx, search, permissionIds, page, pageSize)}
}

func (_c *Service_GetAllPermissionGroups_Call) Run(run func(ctx context.Context, search string, permissionIds []uuid.UUID, page int, pageSize int)) *Service_GetAllPermissionGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]uuid.UUID), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *Service_GetAllPermissionGroups_Call) Return(_a0 []permission.PermissionGroup, _a1 int64, _a2 error) *Service_GetAllPermissionGroups_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Service_GetAllPermissionGroups_Call) RunAndReturn(run func(context.Context, string, []uuid.UUID, int, int) ([]permission.PermissionGroup, int64, error)) *Service_GetAllPermissionGroups_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllPermissions provides a mock function with given fields: ctx, search
func (_m *Service) GetAllPermissions(ctx context.Context, search string) ([]permission.Permission, int64, error) {
	ret := _m.Called(ctx, search)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPermissions")
	}

	var r0 []permission.Permission
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]permission.Permission, int64, error)); ok {
		return rf(ctx, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []permission.Permission); ok {
		r0 = rf(ctx, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]permission.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) int64); ok {
		r1 = rf(ctx, search)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, search)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Service_GetAllPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllPermissions'
type Service_GetAllPermissions_Call struct {
	*mock.Call
}

// GetAllPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
func (_e *Service_Expecter) GetAllPermissions(ctx interface{}, search interface{}) *Service_GetAllPermissions_Call {
	return &Service_GetAllPermissions_Call{Call: _e.mock.On("GetAllPermissions", ctx, search)}
}

func (_c *Service_GetAllPermissions_Call) Run(run func(ctx context.Context, search string)) *Service_GetAllPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Service_GetAllPermissions_Call) Return(_a0 []permission.Permission, _a1 int64, _a2 error) *Service_GetAllPermissions_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Service_GetAllPermissions_Call) RunAndReturn(run func(context.Context, string) ([]permission.Permission, int64, error)) *Service_GetAllPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissionByID provides a mock function with given fields: ctx, id
func (_m *Service) GetPermissionByID(ctx context.Context, id uuid.UUID) (*permission.Permission, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionByID")
	}

	var r0 *permission.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*permission.Permission, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *permission.Permission); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*permission.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetPermissionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissionByID'
type Service_GetPermissionByID_Call struct {
	*mock.Call
}

// GetPermissionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Service_Expecter) GetPermissionByID(ctx interface{}, id interface{}) *Service_GetPermissionByID_Call {
	return &Service_GetPermissionByID_Call{Call: _e.mock.On("GetPermissionByID", ctx, id)}
}

func (_c *Service_GetPermissionByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Service_GetPermissionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Service_GetPermissionByID_Call) Return(_a0 *permission.Permission, _a1 error) *Service_GetPermissionByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetPermissionByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*permission.Permission, error)) *Service_GetPermissionByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissionGroupByID provides a mock function with given fields: ctx, id
func (_m *Service) GetPermissionGroupByID(ctx context.Context, id uuid.UUID) (*permission.PermissionGroup, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionGroupByID")
	}

	var r0 *permission.PermissionGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*permission.PermissionGroup, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *permission.PermissionGroup); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*permission.PermissionGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetPermissionGroupByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissionGroupByID'
type Service_GetPermissionGroupByID_Call struct {
	*mock.Call
}

// GetPermissionGroupByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Service_Expecter) GetPermissionGroupByID(ctx interface{}, id interface{}) *Service_GetPermissionGroupByID_Call {
	return &Service_GetPermissionGroupByID_Call{Call: _e.mock.On("GetPermissionGroupByID", ctx, id)}
}

func (_c *Service_GetPermissionGroupByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Service_GetPermissionGroupByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Service_GetPermissionGroupByID_Call) Return(_a0 *permission.PermissionGroup, _a1 error) *Service_GetPermissionGroupByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetPermissionGroupByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*permission.PermissionGroup, error)) *Service_GetPermissionGroupByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissionGroupsByIDs provides a mock function with given fields: ctx, permissionGroupIds
func (_m *Service) GetPermissionGroupsByIDs(ctx context.Context, permissionGroupIds []uuid.UUID) ([]permission.PermissionGroup, error) {
	ret := _m.Called(ctx, permissionGroupIds)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionGroupsByIDs")
	}

	var r0 []permission.PermissionGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]permission.PermissionGroup, error)); ok {
		return rf(ctx, permissionGroupIds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []permission.PermissionGroup); ok {
		r0 = rf(ctx, permissionGroupIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]permission.PermissionGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, permissionGroupIds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetPermissionGroupsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissionGroupsByIDs'
type Service_GetPermissionGroupsByIDs_Call struct {
	*mock.Call
}

// GetPermissionGroupsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - permissionGroupIds []uuid.UUID
func (_e *Service_Expecter) GetPermissionGroupsByIDs(ctx interface{}, permissionGroupIds interface{}) *Service_GetPermissionGroupsByIDs_Call {
	return &Service_GetPermissionGroupsByIDs_Call{Call: _e.mock.On("GetPermissionGroupsByIDs", ctx, permissionGroupIds)}
}

func (_c *Service_GetPermissionGroupsByIDs_Call) Run(run func(ctx context.Context, permissionGroupIds []uuid.UUID)) *Service_GetPermissionGroupsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *Service_GetPermissionGroupsByIDs_Call) Return(_a0 []permission.PermissionGroup, _a1 error) *Service_GetPermissionGroupsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetPermissionGroupsByIDs_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]permission.PermissionGroup, error)) *Service_GetPermissionGroupsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissionsByIDs provides a mock function with given fields: ctx, permissionIds
func (_m *Service) GetPermissionsByIDs(ctx context.Context, permissionIds []uuid.UUID) ([]permission.Permission, error) {
	ret := _m.Called(ctx, permissionIds)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionsByIDs")
	}

	var r0 []permission.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]permission.Permission, error)); ok {
		return rf(ctx, permissionIds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []permission.Permission); ok {
		r0 = rf(ctx, permissionIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]permission.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, permissionIds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetPermissionsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissionsByIDs'
type Service_GetPermissionsByIDs_Call struct {
	*mock.Call
}

// GetPermissionsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - permissionIds []uuid.UUID
func (_e *Service_Expecter) GetPermissionsByIDs(ctx interface{}, permissionIds interface{}) *Service_GetPermissionsByIDs_Call {
	return &Service_GetPermissionsByIDs_Call{Call: _e.mock.On("GetPermissionsByIDs", ctx, permissionIds)}
}

func (_c *Service_GetPermissionsByIDs_Call) Run(run func(ctx context.Context, permissionIds []uuid.UUID)) *Service_GetPermissionsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *Service_GetPermissionsByIDs_Call) Return(_a0 []permission.Permission, _a1 error) *Service_GetPermissionsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetPermissionsByIDs_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]permission.Permission, error)) *Service_GetPermissionsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserPermissionCodeNames provides a mock function with given fields: ctx, userId
func (_m *Service) GetUserPermissionCodeNames(ctx context.Context, userId uuid.UUID) ([]string, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPermissionCodeNames")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]string, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []string); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetUserPermissionCodeNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPermissionCodeNames'
type Service_GetUserPermissionCodeNames_Call struct {
	*mock.Call
}

// GetUserPermissionCodeNames is a helper method to define mock.On call
//   - ctx context.Context
//   - userId uuid.UUID
func (_e *Service_Expecter) GetUserPermissionCodeNames(ctx interface{}, userId interface{}) *Service_GetUserPermissionCodeNames_Call {
	return &Service_GetUserPermissionCodeNames_Call{Call: _e.mock.On("GetUserPermissionCodeNames", ctx, userId)}
}

func (_c *Service_GetUserPermissionCodeNames_Call) Run(run func(ctx context.Context, userId uuid.UUID)) *Service_GetUserPermissionCodeNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Service_GetUserPermissionCodeNames_Call) Return(_a0 []string, _a1 error) *Service_GetUserPermissionCodeNames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetUserPermissionCodeNames_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]string, error)) *Service_GetUserPermissionCodeNames_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateUserPermissionCache provides a mock function with given fields: ctx, userId
func (_m *Service) InvalidateUserPermissionCache(ctx context.Context, userId uuid.UUID) error {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateUserPermissionCache")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_InvalidateUserPermissionCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateUserPermissionCache'
type Service_InvalidateUserPermissionCache_Call struct {
	*mock.Call
}

// InvalidateUserPermissionCache is a helper method to define mock.On call
//   - ctx context.Context
//   - userId uuid.UUID
func (_e *Service_Expecter) InvalidateUserPermissionCache(ctx interface{}, userId interface{}) *Service_InvalidateUserPermissionCache_Call {
	return &Service_InvalidateUserPermissionCache_Call{Call: _e.mock.On("InvalidateUserPermissionCache", ctx, userId)}
}

func (_c *Service_InvalidateUserPermissionCache_Call) Run(run func(ctx context.Context, userId uuid.UUID)) *Service_InvalidateUserPermissionCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Service_InvalidateUserPermissionCache_Call) Return(_a0 error) *Service_InvalidateUserPermissionCache_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_InvalidateUserPermissionCache_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *Service_InvalidateUserPermissionCache_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePermissionGroup provides a mock function with given fields: ctx, id, permissionGroup
func (_m *Service) UpdatePermissionGroup(ctx context.Context, id uuid.UUID, permissionGroup *permission.PermissionGroupInput) error {
	ret := _m.Called(ctx, id, permissionGroup)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePermissionGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *permission.PermissionGroupInput) error); ok {
		r0 = rf(ctx, id, permissionGroup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_UpdatePermissionGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePermissionGroup'
type Service_UpdatePermissionGroup_Call struct {
	*mock.Call
}

// UpdatePermissionGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - permissionGroup *permission.PermissionGroupInput
func (_e *Service_Expecter) UpdatePermissionGroup(ctx interface{}, id interface{}, permissionGroup interface{}) *Service_UpdatePermissionGroup_Call {
	return &Service_UpdatePermissionGroup_Call{Call: _e.mock.On("UpdatePermissionGroup", ctx, id, permissionGroup)}
}

func (_c *Service_UpdatePermissionGroup_Call) Run(run func(ctx context.Context, id uuid.UUID, permissionGroup *permission.PermissionGroupInput)) *Service_UpdatePermissionGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*permission.PermissionGroupInput))
	})
	return _c
}

func (_c *Service_UpdatePermissionGroup_Call) Return(_a0 error) *Service_UpdatePermissionGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_UpdatePermissionGroup_Call) RunAndReturn(run func(context.Context, uuid.UUID, *permission.PermissionGroupInput) error) *Service_UpdatePermissionGroup_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
