// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	auth "nh-be/internal/features/auth"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CreateVerificationToken provides a mock function with given fields: token
func (_m *Repository) CreateVerificationToken(token *auth.VerificationToken) (auth.VerificationToken, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for CreateVerificationToken")
	}

	var r0 auth.VerificationToken
	var r1 error
	if rf, ok := ret.Get(0).(func(*auth.VerificationToken) (auth.VerificationToken, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(*auth.VerificationToken) auth.VerificationToken); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(auth.VerificationToken)
	}

	if rf, ok := ret.Get(1).(func(*auth.VerificationToken) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CreateVerificationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVerificationToken'
type Repository_CreateVerificationToken_Call struct {
	*mock.Call
}

// CreateVerificationToken is a helper method to define mock.On call
//   - token *auth.VerificationToken
func (_e *Repository_Expecter) CreateVerificationToken(token interface{}) *Repository_CreateVerificationToken_Call {
	return &Repository_CreateVerificationToken_Call{Call: _e.mock.On("CreateVerificationToken", token)}
}

func (_c *Repository_CreateVerificationToken_Call) Run(run func(token *auth.VerificationToken)) *Repository_CreateVerificationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*auth.VerificationToken))
	})
	return _c
}

func (_c *Repository_CreateVerificationToken_Call) Return(_a0 auth.VerificationToken, _a1 error) *Repository_CreateVerificationToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CreateVerificationToken_Call) RunAndReturn(run func(*auth.VerificationToken) (auth.VerificationToken, error)) *Repository_CreateVerificationToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVerificationToken provides a mock function with given fields: token
func (_m *Repository) DeleteVerificationToken(token *auth.VerificationToken) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVerificationToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*auth.VerificationToken) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_DeleteVerificationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVerificationToken'
type Repository_DeleteVerificationToken_Call struct {
	*mock.Call
}

// DeleteVerificationToken is a helper method to define mock.On call
//   - token *auth.VerificationToken
func (_e *Repository_Expecter) DeleteVerificationToken(token interface{}) *Repository_DeleteVerificationToken_Call {
	return &Repository_DeleteVerificationToken_Call{Call: _e.mock.On("DeleteVerificationToken", token)}
}

func (_c *Repository_DeleteVerificationToken_Call) Run(run func(token *auth.VerificationToken)) *Repository_DeleteVerificationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*auth.VerificationToken))
	})
	return _c
}

func (_c *Repository_DeleteVerificationToken_Call) Return(_a0 error) *Repository_DeleteVerificationToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_DeleteVerificationToken_Call) RunAndReturn(run func(*auth.VerificationToken) error) *Repository_DeleteVerificationToken_Call {
	_c.Call.Return(run)
	return _c
}

// FindVerificationTokenByCodeHash provides a mock function with given fields: codeHash
func (_m *Repository) FindVerificationTokenByCodeHash(codeHash string) (*auth.VerificationToken, error) {
	ret := _m.Called(codeHash)

	if len(ret) == 0 {
		panic("no return value specified for FindVerificationTokenByCodeHash")
	}

	var r0 *auth.VerificationToken
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*auth.VerificationToken, error)); ok {
		return rf(codeHash)
	}
	if rf, ok := ret.Get(0).(func(string) *auth.VerificationToken); ok {
		r0 = rf(codeHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.VerificationToken)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(codeHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindVerificationTokenByCodeHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindVerificationTokenByCodeHash'
type Repository_FindVerificationTokenByCodeHash_Call struct {
	*mock.Call
}

// FindVerificationTokenByCodeHash is a helper method to define mock.On call
//   - codeHash string
func (_e *Repository_Expecter) FindVerificationTokenByCodeHash(codeHash interface{}) *Repository_FindVerificationTokenByCodeHash_Call {
	return &Repository_FindVerificationTokenByCodeHash_Call{Call: _e.mock.On("FindVerificationTokenByCodeHash", codeHash)}
}

func (_c *Repository_FindVerificationTokenByCodeHash_Call) Run(run func(codeHash string)) *Repository_FindVerificationTokenByCodeHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repository_FindVerificationTokenByCodeHash_Call) Return(_a0 *auth.VerificationToken, _a1 error) *Repository_FindVerificationTokenByCodeHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindVerificationTokenByCodeHash_Call) RunAndReturn(run func(string) (*auth.VerificationToken, error)) *Repository_FindVerificationTokenByCodeHash_Call {
	_c.Call.Return(run)
	return _c
}

// FindVerificationTokenByUserId provides a mock function with given fields: userId
func (_m *Repository) FindVerificationTokenByUserId(userId uuid.UUID) (*auth.VerificationToken, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for FindVerificationTokenByUserId")
	}

	var r0 *auth.VerificationToken
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*auth.VerificationToken, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *auth.VerificationToken); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.VerificationToken)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindVerificationTokenByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindVerificationTokenByUserId'
type Repository_FindVerificationTokenByUserId_Call struct {
	*mock.Call
}

// FindVerificationTokenByUserId is a helper method to define mock.On call
//   - userId uuid.UUID
func (_e *Repository_Expecter) FindVerificationTokenByUserId(userId interface{}) *Repository_FindVerificationTokenByUserId_Call {
	return &Repository_FindVerificationTokenByUserId_Call{Call: _e.mock.On("FindVerificationTokenByUserId", userId)}
}

func (_c *Repository_FindVerificationTokenByUserId_Call) Run(run func(userId uuid.UUID)) *Repository_FindVerificationTokenByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_FindVerificationTokenByUserId_Call) Return(_a0 *auth.VerificationToken, _a1 error) *Repository_FindVerificationTokenByUserId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindVerificationTokenByUserId_Call) RunAndReturn(run func(uuid.UUID) (*auth.VerificationToken, error)) *Repository_FindVerificationTokenByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
