// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	auth "nh-be/internal/features/auth"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CreateVerificationToken provides a mock function with given fields: ctx, token
func (_m *Repository) CreateVerificationToken(ctx context.Context, token *auth.VerificationToken) (auth.VerificationToken, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for CreateVerificationToken")
	}

	var r0 auth.VerificationToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.VerificationToken) (auth.VerificationToken, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *auth.VerificationToken) auth.VerificationToken); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(auth.VerificationToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *auth.VerificationToken) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CreateVerificationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVerificationToken'
type Repository_CreateVerificationToken_Call struct {
	*mock.Call
}

// CreateVerificationToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *auth.VerificationToken
func (_e *Repository_Expecter) CreateVerificationToken(ctx interface{}, token interface{}) *Repository_CreateVerificationToken_Call {
	return &Repository_CreateVerificationToken_Call{Call: _e.mock.On("CreateVerificationToken", ctx, token)}
}

func (_c *Repository_CreateVerificationToken_Call) Run(run func(ctx context.Context, token *auth.VerificationToken)) *Repository_CreateVerificationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*auth.VerificationToken))
	})
	return _c
}

func (_c *Repository_CreateVerificationToken_Call) Return(_a0 auth.VerificationToken, _a1 error) *Repository_CreateVerificationToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CreateVerificationToken_Call) RunAndReturn(run func(context.Context, *auth.VerificationToken) (auth.VerificationToken, error)) *Repository_CreateVerificationToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVerificationToken provides a mock function with given fields: ctx, token
func (_m *Repository) DeleteVerificationToken(ctx context.Context, token *auth.VerificationToken) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVerificationToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.VerificationToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_DeleteVerificationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVerificationToken'
type Repository_DeleteVerificationToken_Call struct {
	*mock.Call
}

// DeleteVerificationToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *auth.VerificationToken
func (_e *Repository_Expecter) DeleteVerificationToken(ctx interface{}, token interface{}) *Repository_DeleteVerificationToken_Call {
	return &Repository_DeleteVerificationToken_Call{Call: _e.mock.On("DeleteVerificationToken", ctx, token)}
}

func (_c *Repository_DeleteVerificationToken_Call) Run(run func(ctx context.Context, token *auth.VerificationToken)) *Repository_DeleteVerificationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*auth.VerificationToken))
	})
	return _c
}

func (_c *Repository_DeleteVerificationToken_Call) Return(_a0 error) *Repository_DeleteVerificationToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_DeleteVerificationToken_Call) RunAndReturn(run func(context.Context, *auth.VerificationToken) error) *Repository_DeleteVerificationToken_Call {
	_c.Call.Return(run)
	return _c
}

// FindVerificationTokenByCodeHash provides a mock function with given fields: ctx, codeHash
func (_m *Repository) FindVerificationTokenByCodeHash(ctx context.Context, codeHash string) (*auth.VerificationToken, error) {
	ret := _m.Called(ctx, codeHash)

	if len(ret) == 0 {
		panic("no return value specified for FindVerificationTokenByCodeHash")
	}

	var r0 *auth.VerificationToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.VerificationToken, error)); ok {
		return rf(ctx, codeHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.VerificationToken); ok {
		r0 = rf(ctx, codeHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.VerificationToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, codeHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindVerificationTokenByCodeHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindVerificationTokenByCodeHash'
type Repository_FindVerificationTokenByCodeHash_Call struct {
	*mock.Call
}

// FindVerificationTokenByCodeHash is a helper method to define mock.On call
//   - ctx context.Context
//   - codeHash string
func (_e *Repository_Expecter) FindVerificationTokenByCodeHash(ctx interface{}, codeHash interface{}) *Repository_FindVerificationTokenByCodeHash_Call {
	return &Repository_FindVerificationTokenByCodeHash_Call{Call: _e.mock.On("FindVerificationTokenByCodeHash", ctx, codeHash)}
}

func (_c *Repository_FindVerificationTokenByCodeHash_Call) Run(run func(ctx context.Context, codeHash string)) *Repository_FindVerificationTokenByCodeHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_FindVerificationTokenByCodeHash_Call) Return(_a0 *auth.VerificationToken, _a1 error) *Repository_FindVerificationTokenByCodeHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindVerificationTokenByCodeHash_Call) RunAndReturn(run func(context.Context, string) (*auth.VerificationToken, error)) *Repository_FindVerificationTokenByCodeHash_Call {
	_c.Call.Return(run)
	return _c
}

// FindVerificationTokenByUserId provides a mock function with given fields: ctx, userId
func (_m *Repository) FindVerificationTokenByUserId(ctx context.Context, userId uuid.UUID) (*auth.VerificationToken, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for FindVerificationTokenByUserId")
	}

	var r0 *auth.VerificationToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*auth.VerificationToken, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *auth.VerificationToken); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.VerificationToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindVerificationTokenByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindVerificationTokenByUserId'
type Repository_FindVerificationTokenByUserId_Call struct {
	*mock.Call
}

// FindVerificationTokenByUserId is a helper method to define mock.On call
//   - ctx context.Context
//   - userId uuid.UUID
func (_e *Repository_Expecter) FindVerificationTokenByUserId(ctx interface{}, userId interface{}) *Repository_FindVerificationTokenByUserId_Call {
	return &Repository_FindVerificationTokenByUserId_Call{Call: _e.mock.On("FindVerificationTokenByUserId", ctx, userId)}
}

func (_c *Repository_FindVerificationTokenByUserId_Call) Run(run func(ctx context.Context, userId uuid.UUID)) *Repository_FindVerificationTokenByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_FindVerificationTokenByUserId_Call) Return(_a0 *auth.VerificationToken, _a1 error) *Repository_FindVerificationTokenByUserId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindVerificationTokenByUserId_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*auth.VerificationToken, error)) *Repository_FindVerificationTokenByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
