// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	auth "nh-be/internal/features/auth"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function with given fields: ctx, id, changePasswordDto
func (_m *Service) ChangePassword(ctx context.Context, id uuid.UUID, changePasswordDto auth.ChangePasswordDto) error {
	ret := _m.Called(ctx, id, changePasswordDto)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, auth.ChangePasswordDto) error); ok {
		r0 = rf(ctx, id, changePasswordDto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type Service_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - changePasswordDto auth.ChangePasswordDto
func (_e *Service_Expecter) ChangePassword(ctx interface{}, id interface{}, changePasswordDto interface{}) *Service_ChangePassword_Call {
	return &Service_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, id, changePasswordDto)}
}

func (_c *Service_ChangePassword_Call) Run(run func(ctx context.Context, id uuid.UUID, changePasswordDto auth.ChangePasswordDto)) *Service_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(auth.ChangePasswordDto))
	})
	return _c
}

func (_c *Service_ChangePassword_Call) Return(_a0 error) *Service_ChangePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_ChangePassword_Call) RunAndReturn(run func(context.Context, uuid.UUID, auth.ChangePasswordDto) error) *Service_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVerificationToken provides a mock function with given fields: ctx, userId, tokenType
func (_m *Service) CreateVerificationToken(ctx context.Context, userId uuid.UUID, tokenType auth.VerificationTokenType) (auth.CreatedTokenDto, error) {
	ret := _m.Called(ctx, userId, tokenType)

	if len(ret) == 0 {
		panic("no return value specified for CreateVerificationToken")
	}

	var r0 auth.CreatedTokenDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, auth.VerificationTokenType) (auth.CreatedTokenDto, error)); ok {
		return rf(ctx, userId, tokenType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, auth.VerificationTokenType) auth.CreatedTokenDto); ok {
		r0 = rf(ctx, userId, tokenType)
	} else {
		r0 = ret.Get(0).(auth.CreatedTokenDto)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, auth.VerificationTokenType) error); ok {
		r1 = rf(ctx, userId, tokenType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_CreateVerificationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVerificationToken'
type Service_CreateVerificationToken_Call struct {
	*mock.Call
}

// CreateVerificationToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userId uuid.UUID
//   - tokenType auth.VerificationTokenType
func (_e *Service_Expecter) CreateVerificationToken(ctx interface{}, userId interface{}, tokenType interface{}) *Service_CreateVerificationToken_Call {
	return &Service_CreateVerificationToken_Call{Call: _e.mock.On("CreateVerificationToken", ctx, userId, tokenType)}
}

func (_c *Service_CreateVerificationToken_Call) Run(run func(ctx context.Context, userId uuid.UUID, tokenType auth.VerificationTokenType)) *Service_CreateVerificationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(auth.VerificationTokenType))
	})
	return _c
}

func (_c *Service_CreateVerificationToken_Call) Return(_a0 auth.CreatedTokenDto, _a1 error) *Service_CreateVerificationToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_CreateVerificationToken_Call) RunAndReturn(run func(context.Context, uuid.UUID, auth.VerificationTokenType) (auth.CreatedTokenDto, error)) *Service_CreateVerificationToken_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *Service) Login(ctx context.Context, email string, password string) (*auth.UserResponseDto, string, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *auth.UserResponseDto
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*auth.UserResponseDto, string, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *auth.UserResponseDto); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.UserResponseDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, email, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Service_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type Service_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *Service_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *Service_Login_Call {
	return &Service_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *Service_Login_Call) Run(run func(ctx context.Context, email string, password string)) *Service_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Service_Login_Call) Return(_a0 *auth.UserResponseDto, _a1 string, _a2 error) *Service_Login_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Service_Login_Call) RunAndReturn(run func(context.Context, string, string) (*auth.UserResponseDto, string, error)) *Service_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, sessionId
func (_m *Service) Logout(ctx context.Context, sessionId string) error {
	ret := _m.Called(ctx, sessionId)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type Service_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionId string
func (_e *Service_Expecter) Logout(ctx interface{}, sessionId interface{}) *Service_Logout_Call {
	return &Service_Logout_Call{Call: _e.mock.On("Logout", ctx, sessionId)}
}

func (_c *Service_Logout_Call) Run(run func(ctx context.Context, sessionId string)) *Service_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Service_Logout_Call) Return(_a0 error) *Service_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Logout_Call) RunAndReturn(run func(context.Context, string) error) *Service_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// SignUp provides a mock function with given fields: ctx, req
func (_m *Service) SignUp(ctx context.Context, req auth.SignUpDto) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.SignUpDto) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_SignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUp'
type Service_SignUp_Call struct {
	*mock.Call
}

// SignUp is a helper method to define mock.On call
//   - ctx context.Context
//   - req auth.SignUpDto
func (_e *Service_Expecter) SignUp(ctx interface{}, req interface{}) *Service_SignUp_Call {
	return &Service_SignUp_Call{Call: _e.mock.On("SignUp", ctx, req)}
}

func (_c *Service_SignUp_Call) Run(run func(ctx context.Context, req auth.SignUpDto)) *Service_SignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.SignUpDto))
	})
	return _c
}

func (_c *Service_SignUp_Call) Return(_a0 error) *Service_SignUp_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_SignUp_Call) RunAndReturn(run func(context.Context, auth.SignUpDto) error) *Service_SignUp_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmail provides a mock function with given fields: ctx, token
func (_m *Service) VerifyEmail(ctx context.Context, token string) (string, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_VerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmail'
type Service_VerifyEmail_Call struct {
	*mock.Call
}

// VerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *Service_Expecter) VerifyEmail(ctx interface{}, token interface{}) *Service_VerifyEmail_Call {
	return &Service_VerifyEmail_Call{Call: _e.mock.On("VerifyEmail", ctx, token)}
}

func (_c *Service_VerifyEmail_Call) Run(run func(ctx context.Context, token string)) *Service_VerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Service_VerifyEmail_Call) Return(_a0 string, _a1 error) *Service_VerifyEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_VerifyEmail_Call) RunAndReturn(run func(context.Context, string) (string, error)) *Service_VerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
