// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	user "nh-be/internal/features/user"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CheckExistingUser provides a mock function with given fields: ctx, userId
func (_m *Service) CheckExistingUser(ctx context.Context, userId uuid.UUID) (*user.User, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for CheckExistingUser")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*user.User, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *user.User); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_CheckExistingUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckExistingUser'
type Service_CheckExistingUser_Call struct {
	*mock.Call
}

// CheckExistingUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userId uuid.UUID
func (_e *Service_Expecter) CheckExistingUser(ctx interface{}, userId interface{}) *Service_CheckExistingUser_Call {
	return &Service_CheckExistingUser_Call{Call: _e.mock.On("CheckExistingUser", ctx, userId)}
}

func (_c *Service_CheckExistingUser_Call) Run(run func(ctx context.Context, userId uuid.UUID)) *Service_CheckExistingUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Service_CheckExistingUser_Call) Return(_a0 *user.User, _a1 error) *Service_CheckExistingUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_CheckExistingUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*user.User, error)) *Service_CheckExistingUser_Call {
	_c.Call.Return(run)
	return _c
}

// CheckExistingUsers provides a mock function with given fields: ctx, userIds
func (_m *Service) CheckExistingUsers(ctx context.Context, userIds []uuid.UUID) ([]user.User, error) {
	ret := _m.Called(ctx, userIds)

	if len(ret) == 0 {
		panic("no return value specified for CheckExistingUsers")
	}

	var r0 []user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]user.User, error)); ok {
		return rf(ctx, userIds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []user.User); ok {
		r0 = rf(ctx, userIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, userIds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_CheckExistingUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckExistingUsers'
type Service_CheckExistingUsers_Call struct {
	*mock.Call
}

// CheckExistingUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - userIds []uuid.UUID
func (_e *Service_Expecter) CheckExistingUsers(ctx interface{}, userIds interface{}) *Service_CheckExistingUsers_Call {
	return &Service_CheckExistingUsers_Call{Call: _e.mock.On("CheckExistingUsers", ctx, userIds)}
}

func (_c *Service_CheckExistingUsers_Call) Run(run func(ctx context.Context, userIds []uuid.UUID)) *Service_CheckExistingUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *Service_CheckExistingUsers_Call) Return(_a0 []user.User, _a1 error) *Service_CheckExistingUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_CheckExistingUsers_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]user.User, error)) *Service_CheckExistingUsers_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, userInput
func (_m *Service) CreateUser(ctx context.Context, userInput *user.UserInput) error {
	ret := _m.Called(ctx, userInput)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *user.UserInput) error); ok {
		r0 = rf(ctx, userInput)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type Service_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userInput *user.UserInput
func (_e *Service_Expecter) CreateUser(ctx interface{}, userInput interface{}) *Service_CreateUser_Call {
	return &Service_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, userInput)}
}

func (_c *Service_CreateUser_Call) Run(run func(ctx context.Context, userInput *user.UserInput)) *Service_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*user.UserInput))
	})
	return _c
}

func (_c *Service_CreateUser_Call) Return(_a0 error) *Service_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_CreateUser_Call) RunAndReturn(run func(context.Context, *user.UserInput) error) *Service_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUsers provides a mock function with given fields: ctx, ids
func (_m *Service) DeleteUsers(ctx context.Context, ids []uuid.UUID) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUsers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_DeleteUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUsers'
type Service_DeleteUsers_Call struct {
	*mock.Call
}

// DeleteUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *Service_Expecter) DeleteUsers(ctx interface{}, ids interface{}) *Service_DeleteUsers_Call {
	return &Service_DeleteUsers_Call{Call: _e.mock.On("DeleteUsers", ctx, ids)}
}

func (_c *Service_DeleteUsers_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *Service_DeleteUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *Service_DeleteUsers_Call) Return(_a0 error) *Service_DeleteUsers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_DeleteUsers_Call) RunAndReturn(run func(context.Context, []uuid.UUID) error) *Service_DeleteUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function with given fields: ctx, search, page, pageSize
func (_m *Service) GetAllUsers(ctx context.Context, search string, page int, pageSize int) ([]user.UserResponseDto, int64, error) {
	ret := _m.Called(ctx, search, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []user.UserResponseDto
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]user.UserResponseDto, int64, error)); ok {
		return rf(ctx, search, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []user.UserResponseDto); ok {
		r0 = rf(ctx, search, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.UserResponseDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int64); ok {
		r1 = rf(ctx, search, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, search, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Service_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type Service_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
//   - page int
//   - pageSize int
func (_e *Service_Expecter) GetAllUsers(ctx interface{}, search interface{}, page interface{}, pageSize interface{}) *Service_GetAllUsers_Call {
	return &Service_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers", ctx, search, page, pageSize)}
}

func (_c *Service_GetAllUsers_Call) Run(run func(ctx context.Context, search string, page int, pageSize int)) *Service_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *Service_GetAllUsers_Call) Return(_a0 []user.UserResponseDto, _a1 int64, _a2 error) *Service_GetAllUsers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Service_GetAllUsers_Call) RunAndReturn(run func(context.Context, string, int, int) ([]user.UserResponseDto, int64, error)) *Service_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetMe provides a mock function with given fields: ctx, id
func (_m *Service) GetMe(ctx context.Context, id uuid.UUID) (user.MeResponseDto, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMe")
	}

	var r0 user.MeResponseDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (user.MeResponseDto, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) user.MeResponseDto); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(user.MeResponseDto)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetMe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMe'
type Service_GetMe_Call struct {
	*mock.Call
}

// GetMe is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Service_Expecter) GetMe(ctx interface{}, id interface{}) *Service_GetMe_Call {
	return &Service_GetMe_Call{Call: _e.mock.On("GetMe", ctx, id)}
}

func (_c *Service_GetMe_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Service_GetMe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Service_GetMe_Call) Return(_a0 user.MeResponseDto, _a1 error) *Service_GetMe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetMe_Call) RunAndReturn(run func(context.Context, uuid.UUID) (user.MeResponseDto, error)) *Service_GetMe_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserById provides a mock function with given fields: ctx, id
func (_m *Service) GetUserById(ctx context.Context, id uuid.UUID) (user.UserResponseDto, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 user.UserResponseDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (user.UserResponseDto, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) user.UserResponseDto); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(user.UserResponseDto)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserById'
type Service_GetUserById_Call struct {
	*mock.Call
}

// GetUserById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Service_Expecter) GetUserById(ctx interface{}, id interface{}) *Service_GetUserById_Call {
	return &Service_GetUserById_Call{Call: _e.mock.On("GetUserById", ctx, id)}
}

func (_c *Service_GetUserById_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Service_GetUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Service_GetUserById_Call) Return(_a0 user.UserResponseDto, _a1 error) *Service_GetUserById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetUserById_Call) RunAndReturn(run func(context.Context, uuid.UUID) (user.UserResponseDto, error)) *Service_GetUserById_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, id, userInput
func (_m *Service) UpdateUser(ctx context.Context, id uuid.UUID, userInput *user.UserInput) error {
	ret := _m.Called(ctx, id, userInput)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *user.UserInput) error); ok {
		r0 = rf(ctx, id, userInput)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type Service_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userInput *user.UserInput
func (_e *Service_Expecter) UpdateUser(ctx interface{}, id interface{}, userInput interface{}) *Service_UpdateUser_Call {
	return &Service_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, id, userInput)}
}

func (_c *Service_UpdateUser_Call) Run(run func(ctx context.Context, id uuid.UUID, userInput *user.UserInput)) *Service_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*user.UserInput))
	})
	return _c
}

func (_c *Service_UpdateUser_Call) Return(_a0 error) *Service_UpdateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_UpdateUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, *user.UserInput) error) *Service_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
