// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	procedure "nh-be/internal/procedure"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function with given fields: ctx, search, offset, limit, withExperiments
func (_m *Repository) FindAll(ctx context.Context, search string, offset int, limit int, withExperiments bool) ([]procedure.Procedure, int64, error) {
	ret := _m.Called(ctx, search, offset, limit, withExperiments)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []procedure.Procedure
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, bool) ([]procedure.Procedure, int64, error)); ok {
		return rf(ctx, search, offset, limit, withExperiments)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, bool) []procedure.Procedure); ok {
		r0 = rf(ctx, search, offset, limit, withExperiments)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]procedure.Procedure)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, bool) int64); ok {
		r1 = rf(ctx, search, offset, limit, withExperiments)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int, bool) error); ok {
		r2 = rf(ctx, search, offset, limit, withExperiments)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type Repository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
//   - offset int
//   - limit int
//   - withExperiments bool
func (_e *Repository_Expecter) FindAll(ctx interface{}, search interface{}, offset interface{}, limit interface{}, withExperiments interface{}) *Repository_FindAll_Call {
	return &Repository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, search, offset, limit, withExperiments)}
}

func (_c *Repository_FindAll_Call) Run(run func(ctx context.Context, search string, offset int, limit int, withExperiments bool)) *Repository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int), args[4].(bool))
	})
	return _c
}

func (_c *Repository_FindAll_Call) Return(_a0 []procedure.Procedure, _a1 int64, _a2 error) *Repository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_FindAll_Call) RunAndReturn(run func(context.Context, string, int, int, bool) ([]procedure.Procedure, int64, error)) *Repository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id, withSteps, withExperiments
func (_m *Repository) FindByID(ctx context.Context, id uuid.UUID, withSteps bool, withExperiments bool) (*procedure.Procedure, error) {
	ret := _m.Called(ctx, id, withSteps, withExperiments)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *procedure.Procedure
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool, bool) (*procedure.Procedure, error)); ok {
		return rf(ctx, id, withSteps, withExperiments)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool, bool) *procedure.Procedure); ok {
		r0 = rf(ctx, id, withSteps, withExperiments)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*procedure.Procedure)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool, bool) error); ok {
		r1 = rf(ctx, id, withSteps, withExperiments)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type Repository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - withSteps bool
//   - withExperiments bool
func (_e *Repository_Expecter) FindByID(ctx interface{}, id interface{}, withSteps interface{}, withExperiments interface{}) *Repository_FindByID_Call {
	return &Repository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id, withSteps, withExperiments)}
}

func (_c *Repository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID, withSteps bool, withExperiments bool)) *Repository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool), args[3].(bool))
	})
	return _c
}

func (_c *Repository_FindByID_Call) Return(_a0 *procedure.Procedure, _a1 error) *Repository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool, bool) (*procedure.Procedure, error)) *Repository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
