// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	procedure "nh-be/internal/features/procedure"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CreateProcedure provides a mock function with given fields: ctx, _a1
func (_m *Repository) CreateProcedure(ctx context.Context, _a1 *procedure.Procedure) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateProcedure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *procedure.Procedure) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_CreateProcedure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProcedure'
type Repository_CreateProcedure_Call struct {
	*mock.Call
}

// CreateProcedure is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *procedure.Procedure
func (_e *Repository_Expecter) CreateProcedure(ctx interface{}, _a1 interface{}) *Repository_CreateProcedure_Call {
	return &Repository_CreateProcedure_Call{Call: _e.mock.On("CreateProcedure", ctx, _a1)}
}

func (_c *Repository_CreateProcedure_Call) Run(run func(ctx context.Context, _a1 *procedure.Procedure)) *Repository_CreateProcedure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*procedure.Procedure))
	})
	return _c
}

func (_c *Repository_CreateProcedure_Call) Return(_a0 error) *Repository_CreateProcedure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_CreateProcedure_Call) RunAndReturn(run func(context.Context, *procedure.Procedure) error) *Repository_CreateProcedure_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProcedureStep provides a mock function with given fields: ctx, step
func (_m *Repository) CreateProcedureStep(ctx context.Context, step *procedure.ProcedureStep) error {
	ret := _m.Called(ctx, step)

	if len(ret) == 0 {
		panic("no return value specified for CreateProcedureStep")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *procedure.ProcedureStep) error); ok {
		r0 = rf(ctx, step)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_CreateProcedureStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProcedureStep'
type Repository_CreateProcedureStep_Call struct {
	*mock.Call
}

// CreateProcedureStep is a helper method to define mock.On call
//   - ctx context.Context
//   - step *procedure.ProcedureStep
func (_e *Repository_Expecter) CreateProcedureStep(ctx interface{}, step interface{}) *Repository_CreateProcedureStep_Call {
	return &Repository_CreateProcedureStep_Call{Call: _e.mock.On("CreateProcedureStep", ctx, step)}
}

func (_c *Repository_CreateProcedureStep_Call) Run(run func(ctx context.Context, step *procedure.ProcedureStep)) *Repository_CreateProcedureStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*procedure.ProcedureStep))
	})
	return _c
}

func (_c *Repository_CreateProcedureStep_Call) Return(_a0 error) *Repository_CreateProcedureStep_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_CreateProcedureStep_Call) RunAndReturn(run func(context.Context, *procedure.ProcedureStep) error) *Repository_CreateProcedureStep_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProcedure provides a mock function with given fields: ctx, id
func (_m *Repository) DeleteProcedure(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProcedure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_DeleteProcedure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProcedure'
type Repository_DeleteProcedure_Call struct {
	*mock.Call
}

// DeleteProcedure is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Repository_Expecter) DeleteProcedure(ctx interface{}, id interface{}) *Repository_DeleteProcedure_Call {
	return &Repository_DeleteProcedure_Call{Call: _e.mock.On("DeleteProcedure", ctx, id)}
}

func (_c *Repository_DeleteProcedure_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Repository_DeleteProcedure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_DeleteProcedure_Call) Return(_a0 error) *Repository_DeleteProcedure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_DeleteProcedure_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *Repository_DeleteProcedure_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProcedureStep provides a mock function with given fields: ctx, stepId, procedureId
func (_m *Repository) DeleteProcedureStep(ctx context.Context, stepId uuid.UUID, procedureId uuid.UUID) error {
	ret := _m.Called(ctx, stepId, procedureId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProcedureStep")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, stepId, procedureId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_DeleteProcedureStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProcedureStep'
type Repository_DeleteProcedureStep_Call struct {
	*mock.Call
}

// DeleteProcedureStep is a helper method to define mock.On call
//   - ctx context.Context
//   - stepId uuid.UUID
//   - procedureId uuid.UUID
func (_e *Repository_Expecter) DeleteProcedureStep(ctx interface{}, stepId interface{}, procedureId interface{}) *Repository_DeleteProcedureStep_Call {
	return &Repository_DeleteProcedureStep_Call{Call: _e.mock.On("DeleteProcedureStep", ctx, stepId, procedureId)}
}

func (_c *Repository_DeleteProcedureStep_Call) Run(run func(ctx context.Context, stepId uuid.UUID, procedureId uuid.UUID)) *Repository_DeleteProcedureStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_DeleteProcedureStep_Call) Return(_a0 error) *Repository_DeleteProcedureStep_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_DeleteProcedureStep_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *Repository_DeleteProcedureStep_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, search, offset, limit
func (_m *Repository) FindAll(ctx context.Context, search string, offset int, limit int) ([]procedure.Procedure, int64, error) {
	ret := _m.Called(ctx, search, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []procedure.Procedure
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]procedure.Procedure, int64, error)); ok {
		return rf(ctx, search, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []procedure.Procedure); ok {
		r0 = rf(ctx, search, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]procedure.Procedure)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int64); ok {
		r1 = rf(ctx, search, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, search, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type Repository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
//   - offset int
//   - limit int
func (_e *Repository_Expecter) FindAll(ctx interface{}, search interface{}, offset interface{}, limit interface{}) *Repository_FindAll_Call {
	return &Repository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, search, offset, limit)}
}

func (_c *Repository_FindAll_Call) Run(run func(ctx context.Context, search string, offset int, limit int)) *Repository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *Repository_FindAll_Call) Return(_a0 []procedure.Procedure, _a1 int64, _a2 error) *Repository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_FindAll_Call) RunAndReturn(run func(context.Context, string, int, int) ([]procedure.Procedure, int64, error)) *Repository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id, withSteps
func (_m *Repository) FindByID(ctx context.Context, id uuid.UUID, withSteps bool) (*procedure.Procedure, error) {
	ret := _m.Called(ctx, id, withSteps)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *procedure.Procedure
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) (*procedure.Procedure, error)); ok {
		return rf(ctx, id, withSteps)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) *procedure.Procedure); ok {
		r0 = rf(ctx, id, withSteps)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*procedure.Procedure)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool) error); ok {
		r1 = rf(ctx, id, withSteps)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type Repository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - withSteps bool
func (_e *Repository_Expecter) FindByID(ctx interface{}, id interface{}, withSteps interface{}) *Repository_FindByID_Call {
	return &Repository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id, withSteps)}
}

func (_c *Repository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID, withSteps bool)) *Repository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *Repository_FindByID_Call) Return(_a0 *procedure.Procedure, _a1 error) *Repository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) (*procedure.Procedure, error)) *Repository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetStepIDsByProcID provides a mock function with given fields: ctx, procedureId
func (_m *Repository) GetStepIDsByProcID(ctx context.Context, procedureId uuid.UUID) ([]procedure.StepMetadata, error) {
	ret := _m.Called(ctx, procedureId)

	if len(ret) == 0 {
		panic("no return value specified for GetStepIDsByProcID")
	}

	var r0 []procedure.StepMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]procedure.StepMetadata, error)); ok {
		return rf(ctx, procedureId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []procedure.StepMetadata); ok {
		r0 = rf(ctx, procedureId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]procedure.StepMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, procedureId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetStepIDsByProcID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStepIDsByProcID'
type Repository_GetStepIDsByProcID_Call struct {
	*mock.Call
}

// GetStepIDsByProcID is a helper method to define mock.On call
//   - ctx context.Context
//   - procedureId uuid.UUID
func (_e *Repository_Expecter) GetStepIDsByProcID(ctx interface{}, procedureId interface{}) *Repository_GetStepIDsByProcID_Call {
	return &Repository_GetStepIDsByProcID_Call{Call: _e.mock.On("GetStepIDsByProcID", ctx, procedureId)}
}

func (_c *Repository_GetStepIDsByProcID_Call) Run(run func(ctx context.Context, procedureId uuid.UUID)) *Repository_GetStepIDsByProcID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Repository_GetStepIDsByProcID_Call) Return(_a0 []procedure.StepMetadata, _a1 error) *Repository_GetStepIDsByProcID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetStepIDsByProcID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]procedure.StepMetadata, error)) *Repository_GetStepIDsByProcID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProcedure provides a mock function with given fields: ctx, id, _a2
func (_m *Repository) UpdateProcedure(ctx context.Context, id uuid.UUID, _a2 *procedure.Procedure) error {
	ret := _m.Called(ctx, id, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProcedure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *procedure.Procedure) error); ok {
		r0 = rf(ctx, id, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateProcedure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProcedure'
type Repository_UpdateProcedure_Call struct {
	*mock.Call
}

// UpdateProcedure is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - _a2 *procedure.Procedure
func (_e *Repository_Expecter) UpdateProcedure(ctx interface{}, id interface{}, _a2 interface{}) *Repository_UpdateProcedure_Call {
	return &Repository_UpdateProcedure_Call{Call: _e.mock.On("UpdateProcedure", ctx, id, _a2)}
}

func (_c *Repository_UpdateProcedure_Call) Run(run func(ctx context.Context, id uuid.UUID, _a2 *procedure.Procedure)) *Repository_UpdateProcedure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*procedure.Procedure))
	})
	return _c
}

func (_c *Repository_UpdateProcedure_Call) Return(_a0 error) *Repository_UpdateProcedure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateProcedure_Call) RunAndReturn(run func(context.Context, uuid.UUID, *procedure.Procedure) error) *Repository_UpdateProcedure_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProcedureStep provides a mock function with given fields: ctx, stepId, procedureId, step
func (_m *Repository) UpdateProcedureStep(ctx context.Context, stepId uuid.UUID, procedureId uuid.UUID, step *procedure.ProcedureStep) error {
	ret := _m.Called(ctx, stepId, procedureId, step)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProcedureStep")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *procedure.ProcedureStep) error); ok {
		r0 = rf(ctx, stepId, procedureId, step)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateProcedureStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProcedureStep'
type Repository_UpdateProcedureStep_Call struct {
	*mock.Call
}

// UpdateProcedureStep is a helper method to define mock.On call
//   - ctx context.Context
//   - stepId uuid.UUID
//   - procedureId uuid.UUID
//   - step *procedure.ProcedureStep
func (_e *Repository_Expecter) UpdateProcedureStep(ctx interface{}, stepId interface{}, procedureId interface{}, step interface{}) *Repository_UpdateProcedureStep_Call {
	return &Repository_UpdateProcedureStep_Call{Call: _e.mock.On("UpdateProcedureStep", ctx, stepId, procedureId, step)}
}

func (_c *Repository_UpdateProcedureStep_Call) Run(run func(ctx context.Context, stepId uuid.UUID, procedureId uuid.UUID, step *procedure.ProcedureStep)) *Repository_UpdateProcedureStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(*procedure.ProcedureStep))
	})
	return _c
}

func (_c *Repository_UpdateProcedureStep_Call) Return(_a0 error) *Repository_UpdateProcedureStep_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateProcedureStep_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, *procedure.ProcedureStep) error) *Repository_UpdateProcedureStep_Call {
	_c.Call.Return(run)
	return _c
}

// WithTransaction provides a mock function with given fields: ctx, fn
func (_m *Repository) WithTransaction(ctx context.Context, fn func(procedure.Repository) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(procedure.Repository) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type Repository_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(procedure.Repository) error
func (_e *Repository_Expecter) WithTransaction(ctx interface{}, fn interface{}) *Repository_WithTransaction_Call {
	return &Repository_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx, fn)}
}

func (_c *Repository_WithTransaction_Call) Run(run func(ctx context.Context, fn func(procedure.Repository) error)) *Repository_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(procedure.Repository) error))
	})
	return _c
}

func (_c *Repository_WithTransaction_Call) Return(_a0 error) *Repository_WithTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_WithTransaction_Call) RunAndReturn(run func(context.Context, func(procedure.Repository) error) error) *Repository_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
