// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	procedure "nh-be/internal/features/procedure"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CreateProcedure provides a mock function with given fields: ctx, _a1
func (_m *Service) CreateProcedure(ctx context.Context, _a1 *procedure.CreateProcedureDto) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateProcedure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *procedure.CreateProcedureDto) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_CreateProcedure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProcedure'
type Service_CreateProcedure_Call struct {
	*mock.Call
}

// CreateProcedure is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *procedure.CreateProcedureDto
func (_e *Service_Expecter) CreateProcedure(ctx interface{}, _a1 interface{}) *Service_CreateProcedure_Call {
	return &Service_CreateProcedure_Call{Call: _e.mock.On("CreateProcedure", ctx, _a1)}
}

func (_c *Service_CreateProcedure_Call) Run(run func(ctx context.Context, _a1 *procedure.CreateProcedureDto)) *Service_CreateProcedure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*procedure.CreateProcedureDto))
	})
	return _c
}

func (_c *Service_CreateProcedure_Call) Return(_a0 error) *Service_CreateProcedure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_CreateProcedure_Call) RunAndReturn(run func(context.Context, *procedure.CreateProcedureDto) error) *Service_CreateProcedure_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProcedure provides a mock function with given fields: ctx, id
func (_m *Service) DeleteProcedure(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProcedure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_DeleteProcedure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProcedure'
type Service_DeleteProcedure_Call struct {
	*mock.Call
}

// DeleteProcedure is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Service_Expecter) DeleteProcedure(ctx interface{}, id interface{}) *Service_DeleteProcedure_Call {
	return &Service_DeleteProcedure_Call{Call: _e.mock.On("DeleteProcedure", ctx, id)}
}

func (_c *Service_DeleteProcedure_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Service_DeleteProcedure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Service_DeleteProcedure_Call) Return(_a0 error) *Service_DeleteProcedure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_DeleteProcedure_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *Service_DeleteProcedure_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllProcedures provides a mock function with given fields: ctx, search, offset, limit
func (_m *Service) GetAllProcedures(ctx context.Context, search string, offset int, limit int) ([]procedure.ProcedureListResponseDto, int64, error) {
	ret := _m.Called(ctx, search, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAllProcedures")
	}

	var r0 []procedure.ProcedureListResponseDto
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]procedure.ProcedureListResponseDto, int64, error)); ok {
		return rf(ctx, search, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []procedure.ProcedureListResponseDto); ok {
		r0 = rf(ctx, search, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]procedure.ProcedureListResponseDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int64); ok {
		r1 = rf(ctx, search, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, search, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Service_GetAllProcedures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllProcedures'
type Service_GetAllProcedures_Call struct {
	*mock.Call
}

// GetAllProcedures is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
//   - offset int
//   - limit int
func (_e *Service_Expecter) GetAllProcedures(ctx interface{}, search interface{}, offset interface{}, limit interface{}) *Service_GetAllProcedures_Call {
	return &Service_GetAllProcedures_Call{Call: _e.mock.On("GetAllProcedures", ctx, search, offset, limit)}
}

func (_c *Service_GetAllProcedures_Call) Run(run func(ctx context.Context, search string, offset int, limit int)) *Service_GetAllProcedures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *Service_GetAllProcedures_Call) Return(_a0 []procedure.ProcedureListResponseDto, _a1 int64, _a2 error) *Service_GetAllProcedures_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Service_GetAllProcedures_Call) RunAndReturn(run func(context.Context, string, int, int) ([]procedure.ProcedureListResponseDto, int64, error)) *Service_GetAllProcedures_Call {
	_c.Call.Return(run)
	return _c
}

// GetProcedureByID provides a mock function with given fields: ctx, id
func (_m *Service) GetProcedureByID(ctx context.Context, id uuid.UUID) (*procedure.ProcedureResponseDto, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProcedureByID")
	}

	var r0 *procedure.ProcedureResponseDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*procedure.ProcedureResponseDto, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *procedure.ProcedureResponseDto); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*procedure.ProcedureResponseDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetProcedureByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProcedureByID'
type Service_GetProcedureByID_Call struct {
	*mock.Call
}

// GetProcedureByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Service_Expecter) GetProcedureByID(ctx interface{}, id interface{}) *Service_GetProcedureByID_Call {
	return &Service_GetProcedureByID_Call{Call: _e.mock.On("GetProcedureByID", ctx, id)}
}

func (_c *Service_GetProcedureByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Service_GetProcedureByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Service_GetProcedureByID_Call) Return(_a0 *procedure.ProcedureResponseDto, _a1 error) *Service_GetProcedureByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetProcedureByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*procedure.ProcedureResponseDto, error)) *Service_GetProcedureByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProcedure provides a mock function with given fields: ctx, id, _a2
func (_m *Service) UpdateProcedure(ctx context.Context, id uuid.UUID, _a2 *procedure.UpdateProcedureDto) error {
	ret := _m.Called(ctx, id, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProcedure")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *procedure.UpdateProcedureDto) error); ok {
		r0 = rf(ctx, id, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_UpdateProcedure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProcedure'
type Service_UpdateProcedure_Call struct {
	*mock.Call
}

// UpdateProcedure is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - _a2 *procedure.UpdateProcedureDto
func (_e *Service_Expecter) UpdateProcedure(ctx interface{}, id interface{}, _a2 interface{}) *Service_UpdateProcedure_Call {
	return &Service_UpdateProcedure_Call{Call: _e.mock.On("UpdateProcedure", ctx, id, _a2)}
}

func (_c *Service_UpdateProcedure_Call) Run(run func(ctx context.Context, id uuid.UUID, _a2 *procedure.UpdateProcedureDto)) *Service_UpdateProcedure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*procedure.UpdateProcedureDto))
	})
	return _c
}

func (_c *Service_UpdateProcedure_Call) Return(_a0 error) *Service_UpdateProcedure_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_UpdateProcedure_Call) RunAndReturn(run func(context.Context, uuid.UUID, *procedure.UpdateProcedureDto) error) *Service_UpdateProcedure_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProcedureStep provides a mock function with given fields: ctx, procedureId, steps
func (_m *Service) UpdateProcedureStep(ctx context.Context, procedureId uuid.UUID, steps []procedure.UpdateProcedureStepInput) error {
	ret := _m.Called(ctx, procedureId, steps)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProcedureStep")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []procedure.UpdateProcedureStepInput) error); ok {
		r0 = rf(ctx, procedureId, steps)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_UpdateProcedureStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProcedureStep'
type Service_UpdateProcedureStep_Call struct {
	*mock.Call
}

// UpdateProcedureStep is a helper method to define mock.On call
//   - ctx context.Context
//   - procedureId uuid.UUID
//   - steps []procedure.UpdateProcedureStepInput
func (_e *Service_Expecter) UpdateProcedureStep(ctx interface{}, procedureId interface{}, steps interface{}) *Service_UpdateProcedureStep_Call {
	return &Service_UpdateProcedureStep_Call{Call: _e.mock.On("UpdateProcedureStep", ctx, procedureId, steps)}
}

func (_c *Service_UpdateProcedureStep_Call) Run(run func(ctx context.Context, procedureId uuid.UUID, steps []procedure.UpdateProcedureStepInput)) *Service_UpdateProcedureStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]procedure.UpdateProcedureStepInput))
	})
	return _c
}

func (_c *Service_UpdateProcedureStep_Call) Return(_a0 error) *Service_UpdateProcedureStep_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_UpdateProcedureStep_Call) RunAndReturn(run func(context.Context, uuid.UUID, []procedure.UpdateProcedureStepInput) error) *Service_UpdateProcedureStep_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
