// Code generated by mockery v2.53.5. DO NOT EDIT.

package permissionmocks

import (
	context "context"
	permission "nh-be/internal/permission"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreatePermissionGroup provides a mock function with given fields: ctx, permissionGroup
func (_m *Service) CreatePermissionGroup(ctx context.Context, permissionGroup *permission.PermissionGroupInput) error {
	ret := _m.Called(ctx, permissionGroup)

	if len(ret) == 0 {
		panic("no return value specified for CreatePermissionGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *permission.PermissionGroupInput) error); ok {
		r0 = rf(ctx, permissionGroup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePermissionGroup provides a mock function with given fields: ctx, id
func (_m *Service) DeletePermissionGroup(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePermissionGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllPermissionGroups provides a mock function with given fields: ctx, search, permissionIds, page, pageSize
func (_m *Service) GetAllPermissionGroups(ctx context.Context, search string, permissionIds []uuid.UUID, page int, pageSize int) ([]permission.PermissionGroup, int64, error) {
	ret := _m.Called(ctx, search, permissionIds, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPermissionGroups")
	}

	var r0 []permission.PermissionGroup
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []uuid.UUID, int, int) ([]permission.PermissionGroup, int64, error)); ok {
		return rf(ctx, search, permissionIds, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []uuid.UUID, int, int) []permission.PermissionGroup); ok {
		r0 = rf(ctx, search, permissionIds, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]permission.PermissionGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []uuid.UUID, int, int) int64); ok {
		r1 = rf(ctx, search, permissionIds, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, []uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, search, permissionIds, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetAllPermissions provides a mock function with given fields: ctx, search
func (_m *Service) GetAllPermissions(ctx context.Context, search string) ([]permission.Permission, int64, error) {
	ret := _m.Called(ctx, search)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPermissions")
	}

	var r0 []permission.Permission
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]permission.Permission, int64, error)); ok {
		return rf(ctx, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []permission.Permission); ok {
		r0 = rf(ctx, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]permission.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) int64); ok {
		r1 = rf(ctx, search)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, search)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetPermissionByID provides a mock function with given fields: ctx, id
func (_m *Service) GetPermissionByID(ctx context.Context, id uuid.UUID) (*permission.Permission, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionByID")
	}

	var r0 *permission.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*permission.Permission, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *permission.Permission); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*permission.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPermissionGroupByID provides a mock function with given fields: ctx, id
func (_m *Service) GetPermissionGroupByID(ctx context.Context, id uuid.UUID) (*permission.PermissionGroup, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionGroupByID")
	}

	var r0 *permission.PermissionGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*permission.PermissionGroup, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *permission.PermissionGroup); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*permission.PermissionGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPermissionGroupsByIDs provides a mock function with given fields: ctx, permissionGroupIds
func (_m *Service) GetPermissionGroupsByIDs(ctx context.Context, permissionGroupIds []uuid.UUID) ([]permission.PermissionGroup, error) {
	ret := _m.Called(ctx, permissionGroupIds)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionGroupsByIDs")
	}

	var r0 []permission.PermissionGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]permission.PermissionGroup, error)); ok {
		return rf(ctx, permissionGroupIds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []permission.PermissionGroup); ok {
		r0 = rf(ctx, permissionGroupIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]permission.PermissionGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, permissionGroupIds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPermissionsByIDs provides a mock function with given fields: ctx, permissionIds
func (_m *Service) GetPermissionsByIDs(ctx context.Context, permissionIds []uuid.UUID) ([]permission.Permission, error) {
	ret := _m.Called(ctx, permissionIds)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionsByIDs")
	}

	var r0 []permission.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]permission.Permission, error)); ok {
		return rf(ctx, permissionIds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []permission.Permission); ok {
		r0 = rf(ctx, permissionIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]permission.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, permissionIds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserPermissionCodeNames provides a mock function with given fields: ctx, userId
func (_m *Service) GetUserPermissionCodeNames(ctx context.Context, userId uuid.UUID) ([]string, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPermissionCodeNames")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]string, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []string); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePermissionGroup provides a mock function with given fields: ctx, id, permissionGroup
func (_m *Service) UpdatePermissionGroup(ctx context.Context, id uuid.UUID, permissionGroup *permission.PermissionGroupInput) error {
	ret := _m.Called(ctx, id, permissionGroup)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePermissionGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *permission.PermissionGroupInput) error); ok {
		r0 = rf(ctx, id, permissionGroup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
